server:
  port: ${PORT:7143}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/incubacaoDB
    username: incubacao
    password: incubacao2022
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.format_sql: true
      hibernate.type: trace
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false


springdoc:
  api-docs:
    path: /openapi
